// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: router.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Loko.Metro.Api {

  /// <summary>Holder for reflection information generated from router.proto</summary>
  public static partial class RouterReflection {

    #region Descriptor
    /// <summary>File descriptor for router.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RouterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxyb3V0ZXIucHJvdG8SDmxva28ubWV0cm8uYXBpGgxjb21tb24ucHJvdG8i",
            "EwoFVG9rZW4SCgoCaWQYASABKAkikAEKC0xpbmtSZXF1ZXN0EiQKBXRva2Vu",
            "GAEgASgLMhUubG9rby5tZXRyby5hcGkuVG9rZW4SJAoDc3JjGAIgASgLMhcu",
            "bG9rby5tZXRyby5hcGkuU3RhdGlvbhIkCgNkc3QYAyABKAsyFy5sb2tvLm1l",
            "dHJvLmFwaS5TdGF0aW9uEg8KB21lc3NhZ2UYBCABKAkikQEKDEJsb2NrUmVx",
            "dWVzdBIkCgV0b2tlbhgBIAEoCzIVLmxva28ubWV0cm8uYXBpLlRva2VuEiQK",
            "A3NyYxgCIAEoCzIXLmxva28ubWV0cm8uYXBpLlN0YXRpb24SJAoDZHN0GAMg",
            "ASgLMhcubG9rby5tZXRyby5hcGkuU3RhdGlvbhIPCgdtZXNzYWdlGAQgASgJ",
            "IpQBCg9UcmFuc21pdFJlcXVlc3QSJAoFdG9rZW4YASABKAsyFS5sb2tvLm1l",
            "dHJvLmFwaS5Ub2tlbhIkCgNzcmMYAiABKAsyFy5sb2tvLm1ldHJvLmFwaS5T",
            "dGF0aW9uEiQKA2RzdBgDIAEoCzIXLmxva28ubWV0cm8uYXBpLlN0YXRpb24S",
            "DwoHbWVzc2FnZRgEIAEoCSI1Cg1MaXN0ZW5SZXF1ZXN0EiQKBXRva2VuGAEg",
            "ASgLMhUubG9rby5tZXRyby5hcGkuVG9rZW4i7wEKBlNpZ25hbBIkCgNzcmMY",
            "AiABKAsyFy5sb2tvLm1ldHJvLmFwaS5TdGF0aW9uEiQKA2RzdBgDIAEoCzIX",
            "Lmxva28ubWV0cm8uYXBpLlN0YXRpb24SDwoHbWVzc2FnZRgEIAEoCRIvCgdj",
            "b250cm9sGAUgASgOMh4ubG9rby5tZXRyby5hcGkuU2lnbmFsLkNvbnRyb2wi",
            "VwoHQ29udHJvbBIMCghOT1RfVVNFRBAAEgkKBVNUQVJUEAESDQoJVEVSTUlO",
            "QVRFEAISCgoGTElOS0VEEAMSCwoHTUVTU0FHRRAEEgsKB0JMT0NLRUQQBTLd",
            "AgoGUm91dGVyEkEKBVN0YXJ0EhwubG9rby5tZXRyby5hcGkuU3RhcnRSZXF1",
            "ZXN0GhgubG9rby5tZXRyby5hcGkuUmVzcG9uc2UiABI/CgRMaW5rEhsubG9r",
            "by5tZXRyby5hcGkuTGlua1JlcXVlc3QaGC5sb2tvLm1ldHJvLmFwaS5SZXNw",
            "b25zZSIAEkEKBUJsb2NrEhwubG9rby5tZXRyby5hcGkuQmxvY2tSZXF1ZXN0",
            "GhgubG9rby5tZXRyby5hcGkuUmVzcG9uc2UiABJHCghUcmFuc21pdBIfLmxv",
            "a28ubWV0cm8uYXBpLlRyYW5zbWl0UmVxdWVzdBoYLmxva28ubWV0cm8uYXBp",
            "LlJlc3BvbnNlIgASQwoGTGlzdGVuEh0ubG9rby5tZXRyby5hcGkuTGlzdGVu",
            "UmVxdWVzdBoWLmxva28ubWV0cm8uYXBpLlNpZ25hbCIAMAFCIFoeZ2l0aHVi",
            "LmNvbS9sb2tvbW90ZXMvbWV0cm8vYXBpYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Loko.Metro.Api.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Loko.Metro.Api.Token), global::Loko.Metro.Api.Token.Parser, new[]{ "Id" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Loko.Metro.Api.LinkRequest), global::Loko.Metro.Api.LinkRequest.Parser, new[]{ "Token", "Src", "Dst", "Message" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Loko.Metro.Api.BlockRequest), global::Loko.Metro.Api.BlockRequest.Parser, new[]{ "Token", "Src", "Dst", "Message" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Loko.Metro.Api.TransmitRequest), global::Loko.Metro.Api.TransmitRequest.Parser, new[]{ "Token", "Src", "Dst", "Message" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Loko.Metro.Api.ListenRequest), global::Loko.Metro.Api.ListenRequest.Parser, new[]{ "Token" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Loko.Metro.Api.Signal), global::Loko.Metro.Api.Signal.Parser, new[]{ "Src", "Dst", "Message", "Control" }, null, new[]{ typeof(global::Loko.Metro.Api.Signal.Types.Control) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Token : pb::IMessage<Token> {
    private static readonly pb::MessageParser<Token> _parser = new pb::MessageParser<Token>(() => new Token());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Token> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Loko.Metro.Api.RouterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Token() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Token(Token other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Token Clone() {
      return new Token(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    /// <summary>
    /// container id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Token);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Token other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Token other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class LinkRequest : pb::IMessage<LinkRequest> {
    private static readonly pb::MessageParser<LinkRequest> _parser = new pb::MessageParser<LinkRequest>(() => new LinkRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LinkRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Loko.Metro.Api.RouterReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LinkRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LinkRequest(LinkRequest other) : this() {
      token_ = other.token_ != null ? other.token_.Clone() : null;
      src_ = other.src_ != null ? other.src_.Clone() : null;
      dst_ = other.dst_ != null ? other.dst_.Clone() : null;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LinkRequest Clone() {
      return new LinkRequest(this);
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 1;
    private global::Loko.Metro.Api.Token token_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Token Token {
      get { return token_; }
      set {
        token_ = value;
      }
    }

    /// <summary>Field number for the "src" field.</summary>
    public const int SrcFieldNumber = 2;
    private global::Loko.Metro.Api.Station src_;
    /// <summary>
    /// required(id, name)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Station Src {
      get { return src_; }
      set {
        src_ = value;
      }
    }

    /// <summary>Field number for the "dst" field.</summary>
    public const int DstFieldNumber = 3;
    private global::Loko.Metro.Api.Station dst_;
    /// <summary>
    /// required(name, image)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Station Dst {
      get { return dst_; }
      set {
        dst_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 4;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LinkRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LinkRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Token, other.Token)) return false;
      if (!object.Equals(Src, other.Src)) return false;
      if (!object.Equals(Dst, other.Dst)) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (token_ != null) hash ^= Token.GetHashCode();
      if (src_ != null) hash ^= Src.GetHashCode();
      if (dst_ != null) hash ^= Dst.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (token_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Token);
      }
      if (src_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Src);
      }
      if (dst_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Dst);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (token_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Token);
      }
      if (src_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Src);
      }
      if (dst_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Dst);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LinkRequest other) {
      if (other == null) {
        return;
      }
      if (other.token_ != null) {
        if (token_ == null) {
          token_ = new global::Loko.Metro.Api.Token();
        }
        Token.MergeFrom(other.Token);
      }
      if (other.src_ != null) {
        if (src_ == null) {
          src_ = new global::Loko.Metro.Api.Station();
        }
        Src.MergeFrom(other.Src);
      }
      if (other.dst_ != null) {
        if (dst_ == null) {
          dst_ = new global::Loko.Metro.Api.Station();
        }
        Dst.MergeFrom(other.Dst);
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (token_ == null) {
              token_ = new global::Loko.Metro.Api.Token();
            }
            input.ReadMessage(token_);
            break;
          }
          case 18: {
            if (src_ == null) {
              src_ = new global::Loko.Metro.Api.Station();
            }
            input.ReadMessage(src_);
            break;
          }
          case 26: {
            if (dst_ == null) {
              dst_ = new global::Loko.Metro.Api.Station();
            }
            input.ReadMessage(dst_);
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class BlockRequest : pb::IMessage<BlockRequest> {
    private static readonly pb::MessageParser<BlockRequest> _parser = new pb::MessageParser<BlockRequest>(() => new BlockRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BlockRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Loko.Metro.Api.RouterReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockRequest(BlockRequest other) : this() {
      token_ = other.token_ != null ? other.token_.Clone() : null;
      src_ = other.src_ != null ? other.src_.Clone() : null;
      dst_ = other.dst_ != null ? other.dst_.Clone() : null;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockRequest Clone() {
      return new BlockRequest(this);
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 1;
    private global::Loko.Metro.Api.Token token_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Token Token {
      get { return token_; }
      set {
        token_ = value;
      }
    }

    /// <summary>Field number for the "src" field.</summary>
    public const int SrcFieldNumber = 2;
    private global::Loko.Metro.Api.Station src_;
    /// <summary>
    /// required(id, name)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Station Src {
      get { return src_; }
      set {
        src_ = value;
      }
    }

    /// <summary>Field number for the "dst" field.</summary>
    public const int DstFieldNumber = 3;
    private global::Loko.Metro.Api.Station dst_;
    /// <summary>
    /// required(name, image)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Station Dst {
      get { return dst_; }
      set {
        dst_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 4;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BlockRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BlockRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Token, other.Token)) return false;
      if (!object.Equals(Src, other.Src)) return false;
      if (!object.Equals(Dst, other.Dst)) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (token_ != null) hash ^= Token.GetHashCode();
      if (src_ != null) hash ^= Src.GetHashCode();
      if (dst_ != null) hash ^= Dst.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (token_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Token);
      }
      if (src_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Src);
      }
      if (dst_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Dst);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (token_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Token);
      }
      if (src_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Src);
      }
      if (dst_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Dst);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BlockRequest other) {
      if (other == null) {
        return;
      }
      if (other.token_ != null) {
        if (token_ == null) {
          token_ = new global::Loko.Metro.Api.Token();
        }
        Token.MergeFrom(other.Token);
      }
      if (other.src_ != null) {
        if (src_ == null) {
          src_ = new global::Loko.Metro.Api.Station();
        }
        Src.MergeFrom(other.Src);
      }
      if (other.dst_ != null) {
        if (dst_ == null) {
          dst_ = new global::Loko.Metro.Api.Station();
        }
        Dst.MergeFrom(other.Dst);
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (token_ == null) {
              token_ = new global::Loko.Metro.Api.Token();
            }
            input.ReadMessage(token_);
            break;
          }
          case 18: {
            if (src_ == null) {
              src_ = new global::Loko.Metro.Api.Station();
            }
            input.ReadMessage(src_);
            break;
          }
          case 26: {
            if (dst_ == null) {
              dst_ = new global::Loko.Metro.Api.Station();
            }
            input.ReadMessage(dst_);
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class TransmitRequest : pb::IMessage<TransmitRequest> {
    private static readonly pb::MessageParser<TransmitRequest> _parser = new pb::MessageParser<TransmitRequest>(() => new TransmitRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TransmitRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Loko.Metro.Api.RouterReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransmitRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransmitRequest(TransmitRequest other) : this() {
      token_ = other.token_ != null ? other.token_.Clone() : null;
      src_ = other.src_ != null ? other.src_.Clone() : null;
      dst_ = other.dst_ != null ? other.dst_.Clone() : null;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransmitRequest Clone() {
      return new TransmitRequest(this);
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 1;
    private global::Loko.Metro.Api.Token token_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Token Token {
      get { return token_; }
      set {
        token_ = value;
      }
    }

    /// <summary>Field number for the "src" field.</summary>
    public const int SrcFieldNumber = 2;
    private global::Loko.Metro.Api.Station src_;
    /// <summary>
    /// required(id, name)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Station Src {
      get { return src_; }
      set {
        src_ = value;
      }
    }

    /// <summary>Field number for the "dst" field.</summary>
    public const int DstFieldNumber = 3;
    private global::Loko.Metro.Api.Station dst_;
    /// <summary>
    /// required(name, image)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Station Dst {
      get { return dst_; }
      set {
        dst_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 4;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TransmitRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TransmitRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Token, other.Token)) return false;
      if (!object.Equals(Src, other.Src)) return false;
      if (!object.Equals(Dst, other.Dst)) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (token_ != null) hash ^= Token.GetHashCode();
      if (src_ != null) hash ^= Src.GetHashCode();
      if (dst_ != null) hash ^= Dst.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (token_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Token);
      }
      if (src_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Src);
      }
      if (dst_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Dst);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (token_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Token);
      }
      if (src_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Src);
      }
      if (dst_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Dst);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TransmitRequest other) {
      if (other == null) {
        return;
      }
      if (other.token_ != null) {
        if (token_ == null) {
          token_ = new global::Loko.Metro.Api.Token();
        }
        Token.MergeFrom(other.Token);
      }
      if (other.src_ != null) {
        if (src_ == null) {
          src_ = new global::Loko.Metro.Api.Station();
        }
        Src.MergeFrom(other.Src);
      }
      if (other.dst_ != null) {
        if (dst_ == null) {
          dst_ = new global::Loko.Metro.Api.Station();
        }
        Dst.MergeFrom(other.Dst);
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (token_ == null) {
              token_ = new global::Loko.Metro.Api.Token();
            }
            input.ReadMessage(token_);
            break;
          }
          case 18: {
            if (src_ == null) {
              src_ = new global::Loko.Metro.Api.Station();
            }
            input.ReadMessage(src_);
            break;
          }
          case 26: {
            if (dst_ == null) {
              dst_ = new global::Loko.Metro.Api.Station();
            }
            input.ReadMessage(dst_);
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ListenRequest : pb::IMessage<ListenRequest> {
    private static readonly pb::MessageParser<ListenRequest> _parser = new pb::MessageParser<ListenRequest>(() => new ListenRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ListenRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Loko.Metro.Api.RouterReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListenRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListenRequest(ListenRequest other) : this() {
      token_ = other.token_ != null ? other.token_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListenRequest Clone() {
      return new ListenRequest(this);
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 1;
    private global::Loko.Metro.Api.Token token_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Token Token {
      get { return token_; }
      set {
        token_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ListenRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ListenRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Token, other.Token)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (token_ != null) hash ^= Token.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (token_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Token);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (token_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Token);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ListenRequest other) {
      if (other == null) {
        return;
      }
      if (other.token_ != null) {
        if (token_ == null) {
          token_ = new global::Loko.Metro.Api.Token();
        }
        Token.MergeFrom(other.Token);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (token_ == null) {
              token_ = new global::Loko.Metro.Api.Token();
            }
            input.ReadMessage(token_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// required                 src dst
  /// for control=START,        o   y
  /// for control=LINKED,       y   y
  /// for control=MESSAGE       y   y 
  /// </summary>
  public sealed partial class Signal : pb::IMessage<Signal> {
    private static readonly pb::MessageParser<Signal> _parser = new pb::MessageParser<Signal>(() => new Signal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Signal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Loko.Metro.Api.RouterReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Signal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Signal(Signal other) : this() {
      src_ = other.src_ != null ? other.src_.Clone() : null;
      dst_ = other.dst_ != null ? other.dst_.Clone() : null;
      message_ = other.message_;
      control_ = other.control_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Signal Clone() {
      return new Signal(this);
    }

    /// <summary>Field number for the "src" field.</summary>
    public const int SrcFieldNumber = 2;
    private global::Loko.Metro.Api.Station src_;
    /// <summary>
    /// required(id, name, image)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Station Src {
      get { return src_; }
      set {
        src_ = value;
      }
    }

    /// <summary>Field number for the "dst" field.</summary>
    public const int DstFieldNumber = 3;
    private global::Loko.Metro.Api.Station dst_;
    /// <summary>
    /// required(id, name, image)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Station Dst {
      get { return dst_; }
      set {
        dst_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 4;
    private string message_ = "";
    /// <summary>
    /// always optional
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "control" field.</summary>
    public const int ControlFieldNumber = 5;
    private global::Loko.Metro.Api.Signal.Types.Control control_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Loko.Metro.Api.Signal.Types.Control Control {
      get { return control_; }
      set {
        control_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Signal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Signal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Src, other.Src)) return false;
      if (!object.Equals(Dst, other.Dst)) return false;
      if (Message != other.Message) return false;
      if (Control != other.Control) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (src_ != null) hash ^= Src.GetHashCode();
      if (dst_ != null) hash ^= Dst.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Control != 0) hash ^= Control.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (src_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Src);
      }
      if (dst_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Dst);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (Control != 0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Control);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (src_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Src);
      }
      if (dst_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Dst);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Control != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Control);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Signal other) {
      if (other == null) {
        return;
      }
      if (other.src_ != null) {
        if (src_ == null) {
          src_ = new global::Loko.Metro.Api.Station();
        }
        Src.MergeFrom(other.Src);
      }
      if (other.dst_ != null) {
        if (dst_ == null) {
          dst_ = new global::Loko.Metro.Api.Station();
        }
        Dst.MergeFrom(other.Dst);
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Control != 0) {
        Control = other.Control;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            if (src_ == null) {
              src_ = new global::Loko.Metro.Api.Station();
            }
            input.ReadMessage(src_);
            break;
          }
          case 26: {
            if (dst_ == null) {
              dst_ = new global::Loko.Metro.Api.Station();
            }
            input.ReadMessage(dst_);
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
          case 40: {
            control_ = (global::Loko.Metro.Api.Signal.Types.Control) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Signal message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Control {
        [pbr::OriginalName("NOT_USED")] NotUsed = 0,
        [pbr::OriginalName("START")] Start = 1,
        [pbr::OriginalName("TERMINATE")] Terminate = 2,
        [pbr::OriginalName("LINKED")] Linked = 3,
        [pbr::OriginalName("MESSAGE")] Message = 4,
        [pbr::OriginalName("BLOCKED")] Blocked = 5,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
